[package]
name = "build_test"
version = "0.1.0"
authors = ["hatta"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.58"
cc-version = {path = "../"}
